// Generated by CoffeeScript 1.6.2
(function() {
  var THRESHOLD, TIME_UNTIL_LISTEN_AGAIN, gotStream, listen, lookForSnap, sum, throwSnapEvent, watchLoop;

  THRESHOLD = 50000;

  TIME_UNTIL_LISTEN_AGAIN = 1000;

  listen = true;

  sum = function(ar) {
    var n, s;

    s = 0;
    n = ar.length;
    while (n--) {
      s = s + ar[n];
    }
    return s;
  };

  throwSnapEvent = function() {
    var event;

    event = new CustomEvent("snap", {
      bubbles: true,
      cancelable: false
    });
    return window.document.body.dispatchEvent(event);
  };

  gotStream = function(stream) {
    var analyser, context, source;

    context = new webkitAudioContext();
    analyser = context.createAnalyser();
    source = context.createMediaStreamSource(stream);
    source.connect(analyser);
    return watchLoop(analyser);
  };

  watchLoop = function(analyser) {
    var freqByteData, loop_id;

    loop_id = window.webkitRequestAnimationFrame((function() {
      return watchLoop(analyser);
    }));
    freqByteData = new Uint8Array(analyser.frequencyBinCount);
    analyser.getByteFrequencyData(freqByteData);
    if (listen) {
      return lookForSnap(freqByteData);
    }
  };

  lookForSnap = function(freqData) {
    var fsum;

    fsum = sum(freqData);
    if (fsum > THRESHOLD) {
      throwSnapEvent();
      listen = false;
      return window.setTimeout((function() {
        return listen = true;
      }), TIME_UNTIL_LISTEN_AGAIN);
    }
  };

  navigator.webkitGetUserMedia({
    audio: true
  }, gotStream);

}).call(this);
